global:
  hosts:
    domain: localhost
    externalIP: ""
  ingress:
    configureCertmanager: false
    tls:
      enabled: false

certmanager:
  install: false
nginx-ingress:
  enabled: true

gitlab-runner:
  install: false
