global:
  hosts:
    domain: localhost
    externalIP: ""
  ingress:
    configureCertmanager: false
    tls:
      enabled: false

sidekiq:
  replicas:
    all: 1
webservice:
  replicas:
    default: 1
gitlab-shell:
  replicas: 1
registry:
  replicas: 1
kas:
  replicas: 1

certmanager:
  install: false
nginx-ingress:
  enabled: false
gitlab-runner:
  install: false
prometheus:
  install: false
grafana:
  install: false
minio:
  install: false
