# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vm.synced_folder "./shared", "/vagrant_shared", type: "nfs", create: false

  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 6144
    libvirt.cpus = 6
  end

  config.vm.define "RobrodriS" do |server|
    server.vm.hostname = "RobrodriS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.network "forwarded_port", guest: 8888, host: 8888

    server.vm.provision "shell", path: "scripts/server.sh"
  end
end
